// Generated by Codex.
//
// Usage examples:
//   pnpm exec tsx scripts/update-weapon.ts 飓风之龙 幽冥毒皇
//   pnpm exec tsx scripts/update-weapon.ts --write 飓风之龙 幽冥毒皇
//   pnpm exec tsx scripts/update-weapon.ts --write --overwrite 飓风之龙
//
// Default mode is dry-run. Existing MDX files use fill-missing mode and do not
// overwrite manually filled values unless --overwrite is provided. Missing MDX
// files are created only when --write is provided.
import fs from "fs";
import path from "path";
import matter from "gray-matter";

const EXPORT_CONTENT_DIR = path.join(process.cwd(), "refs/Exports/NZM/Content");
const WEAPONS_DIR = path.join(process.cwd(), "data/weapons");
const WEAPON_IMAGE_DIR = path.join(process.cwd(), "public/icons/weapons/normal");
const SKILL_IMAGE_DIR = path.join(process.cwd(), "public/icons/weapons/skills");

const TYPE_BY_ID: Record<number, string> = {
  1: "突击步枪",
  2: "狙击步枪",
  3: "霰弹枪",
  4: "火箭发射器",
  5: "冲锋枪",
  6: "机枪",
  7: "手枪",
  8: "单发榴弹",
  9: "弓箭",
  10: "射手步枪",
  13: "近战武器",
  14: "激光武器",
  15: "喷射器",
  16: "连发榴弹",
};

const ELEMENT_BY_ENUM: Record<string, string> = {
  "EElementEffectType::EDamageType_Kinetic": "物理",
  "EElementEffectType::EDamageType_Fire": "火焰",
  "EElementEffectType::EDamageType_Cryo": "寒冷",
  "EElementEffectType::EDamageType_Shock": "电弧",
  "EElementEffectType::EDamageType_Corrosive": "腐蚀",
  "EElementEffectType::EDamageType_Corossive": "腐蚀",
};

const TOUGHNESS_TYPE_BY_ENUM: Record<string, string> = {
  "EHardStrightWeaknessType::Impulse": "冲击",
  "EHardStrightWeaknessType::Piercing": "贯穿",
  "EHardStrightWeaknessType::Explode": "爆炸",
  "EHardStrightWeaknessType::Explosion": "爆炸",
};

const RARITY_BY_QUALITY: Record<number, string> = {
  2: "稀有",
  3: "史诗",
  4: "传说",
};

const TAG_BY_MECHANISM: Record<string, string> = {
  AutoAim: "自瞄",
  BurstFire: "快速连发",
  ElementAnomaly: "元素异常",
  Explode: "爆炸",
  Explosion: "爆炸",
  Piercing: "穿透",
  ReloadSpeed: "快速装填",
  ThreeBurst: "三连发",
};

type JsonRow = Record<string, any>;
type Rows = Record<string, JsonRow>;

type WeaponFile = {
  file: string;
  filePath: string;
  content: string;
  data: Record<string, any>;
  title: string;
  exists: boolean;
};

type AssetPlan = {
  kind: "weapon" | "skill";
  assetPathName: string;
  sourcePath: string | null;
  destPath: string;
  webPath: string;
};

function readRows(relativePath: string): Rows {
  const filePath = path.join(EXPORT_CONTENT_DIR, relativePath);
  if (!fs.existsSync(filePath)) throw new Error(`Missing export JSON: ${filePath}`);
  const json = JSON.parse(fs.readFileSync(filePath, "utf-8"));
  return (Array.isArray(json) ? json[0]?.Rows : json.Rows) ?? {};
}

function localized(value: any): string | undefined {
  if (!value) return undefined;
  if (typeof value === "string") return value;
  return value.LocalizedString ?? value.SourceString ?? value.CultureInvariantString ?? undefined;
}

function num(value: any): number | undefined {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function round(value: number): number {
  return Number(value.toFixed(4));
}

function ceilToSingleDecimal(value: number): number {
  return Math.ceil(value * 10) / 10;
}

function assetName(assetPathName: string | undefined): string | undefined {
  if (!assetPathName || assetPathName === "None") return undefined;
  return assetPathName.split("/").pop()?.split(".")[0];
}

function assetPathToFile(assetPathName: string | undefined): string | null {
  if (!assetPathName || assetPathName === "None") return null;
  const objectPath = assetPathName.split(".")[0];
  if (!objectPath.startsWith("/Game/")) return null;
  const relativePath = objectPath.slice("/Game/".length).split("/");
  const filePath = path.join(EXPORT_CONTENT_DIR, ...relativePath) + ".png";
  return fs.existsSync(filePath) ? filePath : null;
}

function assetPlan(kind: "weapon" | "skill", assetPathName: string | undefined, destName: string): AssetPlan | undefined {
  if (!assetPathName || assetPathName === "None") return undefined;
  const destDir = kind === "weapon" ? WEAPON_IMAGE_DIR : SKILL_IMAGE_DIR;
  const webDir = kind === "weapon" ? "/icons/weapons/normal" : "/icons/weapons/skills";
  return {
    kind,
    assetPathName,
    sourcePath: assetPathToFile(assetPathName),
    destPath: path.join(destDir, destName),
    webPath: `${webDir}/${destName}`,
  };
}

function uniqueAssets(assets: AssetPlan[]): AssetPlan[] {
  const seen = new Set<string>();
  return assets.filter((asset) => {
    const key = asset.destPath;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function findByField(rows: Rows, field: string, value: any): [string, JsonRow] | undefined {
  const wanted = String(value);
  return Object.entries(rows).find(([, row]) => String(row[field]) === wanted);
}

function prototypeRowByTitle(rows: Rows, title: string): [string, JsonRow] | undefined {
  const keys = [title, `${title}_`];
  for (const key of keys) if (rows[key]) return [key, rows[key]];
  return undefined;
}

function findPrototypeRow(rows: Rows, weapon: WeaponFile): [string, JsonRow] | undefined {
  const prototypeId = weapon.data.prototype_id == null ? undefined : String(weapon.data.prototype_id);
  const matches = Object.entries(rows).filter(([, row]) => prototypeId && String(row.PrototypeID) === prototypeId);
  if (matches.length === 0) return prototypeRowByTitle(rows, weapon.title);
  matches.sort(([, a], [, b]) => {
    if (a.Mode === 0 && b.Mode !== 0) return -1;
    if (a.Mode !== 0 && b.Mode === 0) return 1;
    if (a.ASCTypeID && !b.ASCTypeID) return -1;
    if (!a.ASCTypeID && b.ASCTypeID) return 1;
    return 0;
  });
  return matches[0];
}

function findModelRow(rows: Rows, prototypeId: string): [string, JsonRow] | undefined {
  const matches = Object.entries(rows).filter(([, row]) => String(row.ModelID) === prototypeId);
  matches.sort(([, a], [, b]) => {
    const aBrief = localized(a.BriefDesc);
    const bBrief = localized(b.BriefDesc);
    if (!aBrief && bBrief) return -1;
    if (aBrief && !bBrief) return 1;
    return Number(a.ItemID) - Number(b.ItemID);
  });
  return matches[0];
}

function useTypeForWeaponType(weaponTypeId: number | undefined): string | undefined {
  if (weaponTypeId == null) return undefined;
  if (weaponTypeId === 13) return "近战武器";
  if (weaponTypeId === 7) return "副武器";
  return "主武器";
}

function mechanismTags(rawTags: any[]): string[] {
  return rawTags
    .map((tag) => String(tag?.TagName ?? tag))
    .map((tag) => Object.entries(TAG_BY_MECHANISM).find(([key]) => tag.includes(key))?.[1])
    .filter((tag): tag is string => Boolean(tag));
}

function duration(skillConfig: JsonRow | undefined): number | number[] | undefined {
  const values = (Array.isArray(skillConfig?.Parameters) ? skillConfig.Parameters : [])
    .filter((param: JsonRow) => {
      const tags = String(param.Tags ?? "");
      return tags.includes("EffectDuration") || tags.includes("SummonerDuration");
    })
    .map((param: JsonRow) => num(param.Value))
    .filter((value: number | undefined): value is number => value !== undefined);
  return values.length === 0 ? undefined : values.length === 1 ? values[0] : values;
}

function positiveId(value: any): string | undefined {
  const valueNumber = num(value);
  if (valueNumber == null || valueNumber <= 0) return undefined;
  return String(value);
}

function findNumericalRowById(numericalRows: Rows, value: any): [string, JsonRow] | undefined {
  const id = positiveId(value);
  if (!id) return undefined;

  const exact = numericalRows[`${id}_1`] ? [`${id}_1`, numericalRows[`${id}_1`]] : numericalRows[id] ? [id, numericalRows[id]] : undefined;
  if (exact) return exact as [string, JsonRow];

  return findByField(numericalRows, "id", id);
}

function findNumericalRow(numericalRows: Rows, prototype: JsonRow): [string, JsonRow] | undefined {
  const ids = [
    positiveId(prototype.NumericalID),
    positiveId(prototype.HeavyHitNumericalID),
    positiveId(prototype.LightHitNumericalID),
  ].filter((id): id is string => Boolean(id));

  for (const id of ids) {
    const exact = findNumericalRowById(numericalRows, id);
    if (exact) return exact;
  }

  return undefined;
}

function extractWeapon(weapon: WeaponFile, tables: Record<string, Rows>) {
  const prototypeMatch = findPrototypeRow(tables.prototype, weapon);
  if (!prototypeMatch) throw new Error(`Cannot find WeaponPrototypeConfig row for ${weapon.title}`);
  const [prototypeKey, prototype] = prototypeMatch;
  const prototypeId = String(prototype.PrototypeID);
  const weaponTypeId = num(prototype.WeaponType);
  const ascTypeId = String(prototype.ASCTypeID);
  const asc = tables.asc[ascTypeId] ?? findByField(tables.asc, "ASCTypeID", ascTypeId)?.[1];
  if (!asc) throw new Error(`Cannot find attr_weapon_asc row ${ascTypeId} for ${weapon.title}`);

  const numericalId = prototype.NumericalID;
  const numericalMatch = findNumericalRow(tables.numerical, prototype);
  const numerical = numericalMatch?.[1];
  if (!numerical && weaponTypeId !== 13) throw new Error(`Cannot find numerical_config_equip row ${numericalId}_1 for ${weapon.title}`);
  const lightHitNumerical = weaponTypeId === 13 ? findNumericalRowById(tables.numerical, prototype.LightHitNumericalID)?.[1] : undefined;
  const heavyHitNumerical = weaponTypeId === 13 ? findNumericalRowById(tables.numerical, prototype.HeavyHitNumericalID)?.[1] : undefined;

  const weaponItem = findModelRow(tables.weaponItem, prototypeId)?.[1];
  const commonItem = weaponItem ? tables.commonItem[String(weaponItem.ItemID)] : undefined;
  const luaItem = findModelRow(tables.luaWeaponItem, prototypeId)?.[1];
  const recoilScore = tables.recoilScore[prototypeId];
  const activeSkillId = num(prototype.ActiveSkillID);
  const active = activeSkillId ? tables.skillConfig[`${activeSkillId}_1`] : undefined;
  const activeDescription = activeSkillId ? tables.skillDescription[String(activeSkillId)] : undefined;
  const activeIconAsset = activeSkillId ? tables.skillIcon[String(activeSkillId)]?.ActiveIcon?.AssetPathName : undefined;
  const activeIcon = assetName(activeIconAsset);
  const passive = Object.values(tables.passiveSkillDescription).filter((row) => {
    const asset = row.MGEIcon?.AssetPathName;
    return typeof asset === "string" && asset.includes(`T_Weapon_Skill_${prototypeId}`);
  });
  const quality = num(commonItem?.Quality);
  const weakAdd = num(numerical?.WeaknessDamageAddScale);
  const reloadModId = luaItem?.WeaponMODConfigID == null ? undefined : String(luaItem.WeaponMODConfigID);
  const reloadSourceId = tables.feel[ascTypeId] ? ascTypeId : reloadModId;
  const reloadFeel = reloadSourceId ? tables.feel[reloadSourceId] : undefined;
  const reloadBase = num(reloadFeel?.WeaponChangeClipTimeBase);
  const reloadEndToFire = num(reloadFeel?.WeaponChangeClipEndToFireTime) ?? 0;
  const reloadTime = reloadBase == null ? undefined : ceilToSingleDecimal(reloadBase + reloadEndToFire);

  const title = localized(commonItem?.Name) ?? weaponItem?.WeaponName ?? prototypeKey;
  const weaponIconAsset = commonItem?.IconPath?.LargeIcon?.AssetPathName ?? commonItem?.IconPath?.NormalIcon?.AssetPathName;
  const skillAssets = [activeIconAsset, ...passive.map((row) => row.MGEIcon?.AssetPathName)]
    .map((assetPathName) => {
      const name = assetName(assetPathName);
      return name ? assetPlan("skill", assetPathName, `${name}.png`) : undefined;
    })
    .filter((asset): asset is AssetPlan => Boolean(asset));
  const assets = uniqueAssets([
    assetPlan("weapon", weaponIconAsset, `${title}.png`),
    ...skillAssets,
  ].filter((asset): asset is AssetPlan => Boolean(asset)));

  const fields: Record<string, any> = {
    title,
    use_type: useTypeForWeaponType(weaponTypeId),
    weapon_type_id: weaponTypeId,
    weapon_type: weaponTypeId == null ? undefined : TYPE_BY_ID[weaponTypeId],
    prototype_id: prototypeId,
    asc_type_id: num(ascTypeId) ?? ascTypeId,
    active_skill_id: activeSkillId,
    element: numerical ? ELEMENT_BY_ENUM[String(numerical.ElementType)] ?? weapon.data.element : weapon.data.element,
    rarity: quality == null ? undefined : RARITY_BY_QUALITY[quality],
    scope: localized(luaItem?.Weapon_Scope),
    damage: numerical ? {
      base: num(numerical.HpCalScale),
      impulse: num(numerical.ImpulseBase),
      toughness: num(numerical.ToughnessBase),
      flesh: num(numerical.FleshDamageBase),
      hurtable: num(numerical.HurtableBase),
    } : undefined,
    melee_damage: weaponTypeId === 13 ? {
      light: num(lightHitNumerical?.HpCalScale ?? numerical?.HpCalScale),
      heavy: num(heavyHitNumerical?.HpCalScale ?? numerical?.HpCalScale),
    } : undefined,
    toughness_type: numerical ? TOUGHNESS_TYPE_BY_ENUM[String(numerical.ToughnessDamageType)] : undefined,
    enable_critical: numerical?.bEnableCriticalDamage,
    weekness_multiplier: numerical?.EnableWeaknessDamage && weakAdd != null ? round(1 + weakAdd) : null,
    fire_interval: num(asc.FireIntervalBase),
    magazine: num(asc.ClipAmmoCountBase),
    total_ammo: num(asc.MaxAmmoCount),
    accuracy: num(recoilScore?.WeaponAccuracy ?? luaItem?.AccuracyInt),
    stability: num(recoilScore?.WeaponStability ?? luaItem?.StabilityInt),
    reload_time: reloadTime,
    attenuation_begin: num(asc.DistanceBeginAttenuationBase) == null ? undefined : round(Number(asc.DistanceBeginAttenuationBase) / 100),
    attenuation_end: num(asc.DistanceEndAttenuationBase) == null ? undefined : round(Number(asc.DistanceEndAttenuationBase) / 100),
    attenuation_scale: num(asc.AttenuationMinScale),
    ignore_shield: numerical?.bDamageIgnoreShield,
    element_add_rate: num(numerical?.ElementAddRate),
    skill_cooldown: num(active?.ChargeNeedTime),
    pellets: (num(asc.SplinterNum) ?? 0) > 1 ? num(asc.SplinterNum) : undefined,
  };
  for (const key of Object.keys(fields)) if (fields[key] === undefined) delete fields[key];

  return {
    fields,
    assets,
    reloadTimeDetail: reloadBase == null ? undefined : {
      base: reloadBase,
      endToFire: reloadEndToFire,
      inGameDisplay: reloadTime,
    },
    source: {
      prototype: `WeaponPrototypeConfig.Rows.${prototypeKey}`,
      asc: `attr_weapon_asc.Rows.${ascTypeId}`,
      numerical: numericalMatch ? `numerical_config_equip.Rows.${numericalMatch[0]}` : undefined,
      weaponItem: weaponItem ? `WeaponItemTable.ModelID=${prototypeId}` : undefined,
      commonItem: commonItem ? `CommonItemDataTable.Rows.${weaponItem?.ItemID}` : undefined,
      luaItem: luaItem ? `LuaDataTable/WeaponItemConfigTable.ModelID=${prototypeId}` : undefined,
      recoilScore: recoilScore ? `Weapon/WeaponRecoilScoreTable.Rows.${prototypeId}` : undefined,
      reload: reloadFeel ? `WeaponFeelParamTable.Rows.${reloadSourceId}` : undefined,
    },
    skills: { active, activeDescription, activeIcon, passive, mechanismTags: mechanismTags(prototype.WeaponMechanismTags ?? []) },
  };
}

function jsxAttribute(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function mdxText(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/\{/g, "&#123;")
    .replace(/\}/g, "&#125;");
}

function unresolvedTemplate(value: string): string {
  return `？${mdxText(value)}？`;
}

function mdxDescription(raw: string | undefined): string {
  if (!raw) return "技能描述信息(待更新)";
  return raw
    .replace(/[\u200b\u200c\ufeff]/g, "")
    .replace(/\r\n/g, "\n")
    .replace(/\{[^}]+\}/g, (value) => unresolvedTemplate(value))
    .replace(/<qiangdiao>([\s\S]*?)<\/?>/g, "<Yellow>$1</Yellow>")
    .replace(/<T\d+>([\s\S]*?)<\/?>/g, "<Blue>$1</Blue>")
    .replace(/<(?!\/?(?:Yellow|Blue)\b)[^>]+>/g, "")
    .trim() || "技能描述信息(待更新)";
}

function indentedDescription(raw: string | undefined): string {
  return mdxDescription(raw)
    .split("\n")
    .map((line) => `    ${line.trim()}`)
    .join("\n");
}

function skillIconPath(iconName: string | undefined): string {
  return iconName ? `/icons/weapons/skills/${iconName}.png` : "/icons/weapons/skills/T_Weapon_Skill_effect_01.png";
}

function jsxNumberProp(name: string, value: any): string | undefined {
  const numberValue = num(value);
  return numberValue == null ? undefined : `${name}={${numberValue}}`;
}

function activeSkillMdx(skills: any): string | undefined {
  const name = localized(skills.activeDescription?.SkillName) ?? skills.active?.SkillName;
  const description = localized(skills.activeDescription?.SkillDescription);
  if (!name && !description && !skills.activeIcon) return undefined;

  const props = [
    `name="${jsxAttribute(String(name ?? "主动技能"))}"`,
    `icon="${jsxAttribute(skillIconPath(skills.activeIcon))}"`,
    typeof duration(skills.active) === "number" ? `duration={${duration(skills.active)}}` : undefined,
    jsxNumberProp("cooldown", skills.active?.ChargeNeedTime),
    jsxNumberProp("count", skills.active?.SkillCount),
  ].filter((prop): prop is string => Boolean(prop));

  return [
    "  <ActiveSkill",
    ...props.map((prop) => `    ${prop}`),
    "  >",
    indentedDescription(description),
    "  </ActiveSkill>",
  ].join("\n");
}

function passiveSkillMdx(row: JsonRow, fallbackTag: string | undefined): string {
  const name = localized(row.MGEName) ?? "被动技能";
  const description = localized(row.MGEDescription);
  const icon = assetName(row.MGEIcon?.AssetPathName);
  const tag = fallbackTag ? `tag="${jsxAttribute(fallbackTag)}"` : undefined;
  const props = [
    `name="${jsxAttribute(name)}"`,
    tag,
    `icon="${jsxAttribute(skillIconPath(icon))}"`,
  ].filter((prop): prop is string => Boolean(prop));

  return [
    "  <PassiveSkill",
    ...props.map((prop) => `    ${prop}`),
    "  >",
    indentedDescription(description),
    "  </PassiveSkill>",
  ].join("\n");
}

function buildSkillMdx(skills: any): string {
  const blocks = [
    activeSkillMdx(skills),
    ...skills.passive.map((row: JsonRow) => passiveSkillMdx(row, skills.mechanismTags[0])),
  ].filter((block): block is string => Boolean(block));

  if (blocks.length === 0) return "";
  return ["<WeaponSkill>", blocks.join("\n\n"), "</WeaponSkill>"].join("\n");
}

function applySkillBody(content: string, skillMdx: string): { content: string; changed: boolean } {
  if (!skillMdx || content.includes("<WeaponSkill>")) return { content, changed: false };
  return { content: `${content.replace(/\s*$/, "")}\n\n${skillMdx}\n`, changed: true };
}
function yamlScalar(value: any): string {
  if (value === null) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  const textValue = String(value);
  if (/^[\w\u4e00-\u9fff .:/+-]+$/.test(textValue) && textValue !== "") return textValue;
  return `'${textValue.replace(/'/g, "''")}'`;
}

function yamlValue(key: string, value: any): string[] {
  if (key === "prototype_id") return [`${key}: '${String(value).replace(/'/g, "''")}'`];
  if (key === "damage" && value && typeof value === "object") {
    return [
      "damage:",
      `  base: ${yamlScalar(value.base)}`,
      `  impulse: ${yamlScalar(value.impulse)}`,
      `  toughness: ${yamlScalar(value.toughness)}`,
      `  flesh: ${yamlScalar(value.flesh)}`,
      `  hurtable: ${yamlScalar(value.hurtable)}`,
    ];
  }
  if (key === "melee_damage" && value && typeof value === "object") {
    return [
      "melee_damage:",
      `  light: ${yamlScalar(value.light)}`,
      `  heavy: ${yamlScalar(value.heavy)}`,
    ];
  }
  return [`${key}: ${yamlScalar(value)}`];
}

function yamlBlockEnd(lines: string[], index: number): number {
  let end = index + 1;
  while (end < lines.length && /^\s+/.test(lines[end])) end++;
  return end;
}

function replaceYamlBlock(lines: string[], key: string, value: any, insertAfter: string): boolean {
  const index = lines.findIndex((line) => line.startsWith(`${key}:`));
  const replacement = yamlValue(key, value);
  if (index >= 0) {
    const end = yamlBlockEnd(lines, index);
    if (lines.slice(index, end).join("\n") === replacement.join("\n")) return false;
    lines.splice(index, end - index, ...replacement);
    return true;
  }
  const anchorIndex = lines.findIndex((line) => line.startsWith(`${insertAfter}:`));
  const insertIndex = anchorIndex >= 0 ? yamlBlockEnd(lines, anchorIndex) : lines.length;
  lines.splice(insertIndex, 0, ...replacement);
  return true;
}

function isEmptyValue(value: any): boolean {
  if (value == null) return true;
  if (typeof value === "string") return value.trim() === "";
  if (Array.isArray(value)) return value.length === 0;
  return false;
}

function shouldApplyField(currentData: Record<string, any>, key: string, overwrite: boolean): boolean {
  if (overwrite) return true;
  if (!(key in currentData)) return true;
  return isEmptyValue(currentData[key]);
}

function updateFrontmatter(content: string, fields: Record<string, any>, currentData: Record<string, any>, overwrite: boolean) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) throw new Error("MDX file has no frontmatter block");
  const lines = match[1].split(/\r?\n/);
  const changedKeys: string[] = [];
  const order = [
    ["title", "title"],
    ["use_type", "title"],
    ["weapon_type_id", "tags"],
    ["prototype_id", "weapon_type_id"],
    ["asc_type_id", "prototype_id"],
    ["active_skill_id", "asc_type_id"],
    ["weapon_type", "use_type"],
    ["element", "weapon_type"],
    ["rarity", "element"],
    ["scope", "tags"],
    ["damage", "active_skill_id"],
    ["melee_damage", "damage"],
    ["toughness_type", "melee_damage"],
    ["enable_critical", "toughness_type"],
    ["weekness_multiplier", "enable_critical"],
    ["fire_interval", "weekness_multiplier"],
    ["magazine", "fire_interval"],
    ["total_ammo", "magazine"],
    ["accuracy", "total_ammo"],
    ["stability", "accuracy"],
    ["reload_time", "stability"],
    ["attenuation_begin", "explosion_range"],
    ["attenuation_end", "attenuation_begin"],
    ["attenuation_scale", "attenuation_end"],
    ["ignore_shield", "attenuation_scale"],
    ["element_add_rate", "ignore_shield"],
    ["skill_cooldown", "element_add_rate"],
    ["pellets", "skill_cooldown"],
  ];
  for (const [key, anchor] of order) {
    if (key in fields && shouldApplyField(currentData, key, overwrite) && replaceYamlBlock(lines, key, fields[key], anchor)) {
      changedKeys.push(key);
    }
  }
  const body = content.slice(match[0].length);
  return { content: `---\n${lines.join("\n")}\n---\n\n${body.replace(/^\r?\n/, "")}`, changedKeys };
}

function loadAllWeaponFiles(): WeaponFile[] {
  return fs.readdirSync(WEAPONS_DIR)
    .filter((file) => file.endsWith(".mdx"))
    .map((file) => {
      const filePath = path.join(WEAPONS_DIR, file);
      const content = fs.readFileSync(filePath, "utf-8");
      const { data } = matter(content);
      return { file, filePath, content, data, title: String(data.title ?? file.replace(/\.mdx$/, "")), exists: true };
    });
}

function editDistance(a: string, b: string): number {
  const dp = Array.from({ length: a.length + 1 }, () => Array<number>(b.length + 1).fill(0));
  for (let i = 0; i <= a.length; i++) dp[i][0] = i;
  for (let j = 0; j <= b.length; j++) dp[0][j] = j;
  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      dp[i][j] = Math.min(
        dp[i - 1][j] + 1,
        dp[i][j - 1] + 1,
        dp[i - 1][j - 1] + cost,
      );
    }
  }
  return dp[a.length][b.length];
}

function suggestions(input: string, weapons: WeaponFile[], extraNames: string[] = []): string[] {
  const lower = input.toLowerCase();
  const titles = [...new Set([...weapons.map((weapon) => weapon.title), ...extraNames])];
  return titles
    .map((title) => {
      const distance = editDistance(input, title);
      const contains = title.includes(input) || input.includes(title) || title.toLowerCase().includes(lower);
      return { title, score: contains ? -1 : distance };
    })
    .filter((item) => item.score <= Math.max(2, Math.ceil(input.length / 2)))
    .sort((a, b) => a.score - b.score || a.title.localeCompare(b.title, "zh-CN"))
    .slice(0, 5)
    .map((item) => item.title);
}

function createWeaponFile(title: string): WeaponFile {
  return {
    file: `${title}.mdx`,
    filePath: path.join(WEAPONS_DIR, `${title}.mdx`),
    content: `---\ntitle: ${title}\n---\n\n`,
    data: { title },
    title,
    exists: false,
  };
}

function selectWeapons(allWeapons: WeaponFile[], names: string[], includeMelee: boolean, prototypeRows: Rows): WeaponFile[] {
  if (names.length === 0) return allWeapons.filter((weapon) => includeMelee || weapon.data.use_type !== "近战武器");

  const selected: WeaponFile[] = [];
  const missing: string[] = [];
  for (const name of names) {
    const match = allWeapons.find((weapon) => weapon.title === name || weapon.file.replace(/\.mdx$/, "") === name);
    if (match) selected.push(match);
    else if (prototypeRowByTitle(prototypeRows, name)) selected.push(createWeaponFile(name));
    else missing.push(name);
  }

  if (missing.length > 0) {
    for (const name of missing) {
      const near = suggestions(name, allWeapons, Object.keys(prototypeRows));
      console.error(`未找到武器：${name}${near.length > 0 ? `。你是不是想输入：${near.join("、")}` : ""}`);
    }
    process.exit(1);
  }

  return selected;
}

function copyAssets(assets: AssetPlan[], write: boolean) {
  return assets.map((asset) => {
    if (!asset.sourcePath) return { ...asset, status: "missing-source" };
    if (!write) return { ...asset, status: fs.existsSync(asset.destPath) ? "exists" : "would-copy" };
    fs.mkdirSync(path.dirname(asset.destPath), { recursive: true });
    fs.copyFileSync(asset.sourcePath, asset.destPath);
    return { ...asset, status: "copied" };
  });
}

function main() {
  const args = process.argv.slice(2);
  const write = args.includes("--write");
  const overwrite = args.includes("--overwrite");
  const includeMelee = args.includes("--include-melee");
  const names = args.filter((arg) => !arg.startsWith("--"));
  const allWeapons = loadAllWeaponFiles();

  const tables = {
    prototype: readRows("DataTables/WeaponPrototypeConfig.json"),
    asc: readRows("Attributes/AutoGenerate/attr_weapon_asc.json"),
    numerical: readRows("DataTables/numerical_config_equip.json"),
    weaponItem: readRows("DataTables/WeaponItemTable.json"),
    commonItem: readRows("DataTables/System/Items/CommonItemDataTable.json"),
    luaWeaponItem: readRows("DataTables/LuaDataTable/WeaponItemConfigTable.json"),
    recoilScore: readRows("DataTables/Weapon/WeaponRecoilScoreTable.json"),
    feel: readRows("DataTables/WeaponFeelParamTable.json"),
    skillConfig: readRows("DataTables/SkillConfigTable_Weapon_PVE.json"),
    skillDescription: readRows("DataTables/Ability/SkillDesConfig_Skill.json"),
    skillIcon: readRows("DataTables/GPSkillIconResourceDataTable.json"),
    passiveSkillDescription: readRows("DataTables/MGE/DT_GPMGESkillDesConfig_Weapon.json"),
  };

  const weapons = selectWeapons(allWeapons, names, includeMelee, tables.prototype);

  const changed: { title: string; keys: string[] }[] = [];
  const created: string[] = [];
  const failed: { title: string; error: string }[] = [];
  const assetResults: ReturnType<typeof copyAssets> = [];

  for (const weapon of weapons) {
    try {
      const extracted = extractWeapon(weapon, tables);
      const frontmatterResult = updateFrontmatter(weapon.content, extracted.fields, weapon.data, overwrite || !weapon.exists);
      const skillResult = applySkillBody(frontmatterResult.content, buildSkillMdx(extracted.skills));
      const result = {
        content: skillResult.content,
        changedKeys: skillResult.changed ? [...frontmatterResult.changedKeys, "skills"] : frontmatterResult.changedKeys,
      };
      if (result.changedKeys.length > 0 || !weapon.exists) {
        if (weapon.exists) changed.push({ title: weapon.title, keys: result.changedKeys });
        else created.push(weapon.title);
        if (write) fs.writeFileSync(weapon.filePath, result.content, "utf-8");
      }
      assetResults.push(...copyAssets(extracted.assets, write));

      if (names.length > 0) {
        console.log(JSON.stringify({
          title: weapon.title,
          mode: weapon.exists ? (overwrite ? "overwrite" : "fill-missing") : "create",
          changedKeys: result.changedKeys,
          fields: extracted.fields,
          reloadTimeDetail: extracted.reloadTimeDetail,
          source: extracted.source,
          assets: extracted.assets.map((asset) => ({
            kind: asset.kind,
            sourcePath: asset.sourcePath,
            webPath: asset.webPath,
          })),
          skills: {
            activeName: localized(extracted.skills.activeDescription?.SkillName) ?? extracted.skills.active?.SkillName,
            activeDescription: localized(extracted.skills.activeDescription?.SkillDescription),
            activeIcon: extracted.skills.activeIcon,
            duration: duration(extracted.skills.active),
            cooldown: extracted.skills.active?.ChargeNeedTime,
            count: extracted.skills.active?.SkillCount,
            mechanismTags: extracted.skills.mechanismTags,
            passive: extracted.skills.passive.map((row) => ({
              name: localized(row.MGEName),
              description: localized(row.MGEDescription),
              icon: assetName(row.MGEIcon?.AssetPathName),
            })),
          },
        }, null, 2));
      }
    } catch (error) {
      failed.push({ title: weapon.title, error: error instanceof Error ? error.message : String(error) });
    }
  }

  console.log(`${write ? "Updated" : "Dry-run"} ${changed.length}/${weapons.length} existing weapon files, ${created.length} new weapon files.`);
  console.log(`${write ? "Copied" : "Checked"} ${assetResults.length} image assets.`);
  console.log("Usage: pnpm exec tsx scripts/update-weapon.ts [--write] [--overwrite] 武器名1 武器名2 ...");
  console.log("Default existing-file mode is fill-missing. Use --overwrite to replace generated frontmatter fields.");
  console.log("Use --include-melee only when running without names and you also want melee pages.");
  for (const title of created.slice(0, 20)) console.log(`- create: ${title}`);
  if (created.length > 20) console.log(`... ${created.length - 20} more new files`);
  for (const item of changed.slice(0, 20)) console.log(`- ${item.title}: ${item.keys.join(", ")}`);
  if (changed.length > 20) console.log(`... ${changed.length - 20} more changed files`);

  const missingAssets = assetResults.filter((asset) => asset.status === "missing-source");
  if (missingAssets.length > 0) {
    console.error(`Missing ${missingAssets.length} image sources:`);
    for (const asset of missingAssets.slice(0, 20)) console.error(`- ${asset.assetPathName} -> ${asset.webPath}`);
    if (missingAssets.length > 20) console.error(`... ${missingAssets.length - 20} more missing image sources`);
    process.exitCode = 1;
  }

  if (failed.length > 0) {
    console.error(`Failed ${failed.length} weapon files:`);
    for (const item of failed.slice(0, 20)) console.error(`- ${item.title}: ${item.error}`);
    process.exitCode = 1;
  }
}

main();